version: "3.7"

services:
  postgresd:
    image: postgres
    container_name: kratos-postgresd
    ports:
      - "15432:5432"
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
        read_only: false
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=kratos
    networks:
      - intranet

  kratos-migrate:
    image: kratos-migrate
    container_name: kratos-migrate
    build:
      context: ../kratos
      dockerfile: ./.docker/Dockerfile-build
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: migrate sql -e --yes
    depends_on:
      - postgresd
    networks:
      - intranet

  kratos:
    image: kratos
    container_name: kratos
    build:
      context: ../kratos
      dockerfile: ./.docker/Dockerfile-debug
      args:
        # do not run docker-compose from the debug folder.
        # instead, run `make r-start` from the root folder of the project(dev-kratos).
        - source_dir=${PWD}/kratos
    depends_on:
      - kratos-migrate
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
      - "9000:40000"
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    command: serve -c /etc/config/kratos/kratos.yml --watch-courier --dev
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos/
      - type: bind
        source: ../kratos
        target: ${PWD}/kratos
        read_only: false
    networks:
      - intranet

  mailslurper:
    container_name: kratoss-mailslurper
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

  kratos-admin-ui:
    container_name: kratos-admin-ui
    image: kratos-admin-ui
    build:
      context: ../kratos-admin-ui
      dockerfile: ./Dockerfile
    ports:
      - "6060:80"
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
    networks:
      - intranet

volumes:
  postgres-db:
networks:
  intranet:
